### ISSUE TITLE
Sensor doesn't work

### ISSUE THREAD

**Issue by Sildenafil99** [PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net#1]
Hi,
I've installed the custom component. Home assistant show me the new sensor, but the only one that works is the storms_nearby.
Now it's raining and storming but the sensor are off.
My configuration:
- platform: burze_dzis_net
    api_key: !secret burze_api
    latitude: !secret latitude
    longitude: !secret longitude
    warnings:
      - wind_warning
      - precipitation_warning
      - storm_warning
      - tornado_warning
    storms_nearby:
      radius: 15

**Comment by PiotrMachowski** [comment]
Hi,
There are 2 possible reasons why this sensor doesn't work for you:
- website [Burze.dzis.net](https://burze.dzis.net/?page=home) provides warnings only for Poland
- API provides information about severe weather hazards, not current weather
In both cases it is not issue with sensor, but with API
