### ISSUE TITLE
Problem with the memory usage - increase

### ISSUE THREAD

**Issue by PiterPiotr** [PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net#17]
I have a Home Assistant on RPi4 with 4 GB of RAM.
Since spring is coming, so storms, I decided to add the burze_dzis_net integration.
I uploaded the folder with integration to custom_components (then restart), I added sensors to the .yaml file (restart again) and sensors appeared. After 24 hours, I saw that the memory usage had increased from 22% to over 30% and was growing. I removed the integration, waited and confirmed that it was a problem with this integration. Below scr .
![Bez tytułu](https://user-images.githubusercontent.com/94084387/156932243-4abdef74-33d1-417d-bd52-5a2d4e8b6bce.jpg)
:

**Comment by cichytom** [comment]
I have exactly the same problem.
[https://ai-speaker.discourse.group/t/utylizacja-ram-na-bramce-i-automatyczny-restart/2118](url)

**Comment by nepozs** [comment]
Configuration where I can't find this memory leak (maybe it can help with investigation):
## System Health

version | core-2022.3.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.98
arch | x86_64
timezone | Europe/Warsaw

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4988
Installed Version | 1.23.0
Stage | running
Available Repositories | 1016
Downloaded Repositories | 67

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>GIOŚ</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.4
docker_version | 20.10.9
disk_total | 14.0 GB
disk_used | 10.9 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), SSH & Web Terminal (10.0.2), Samba share (9.5.1), ZeroTier One (0.12.2), FTP (4.4.1), Check Home Assistant configuration (3.10.0), Mosquitto broker (6.0.1), Zigbee2mqtt (1.24.0-1), Tasmota Device Manager (2022.2.0), HDD Tools (0.52.0), Tailscale (0.5.4), VLC (0.1.3), motionEye (0.17.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 35
views | 25
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

<details><summary>Żadnego Ale</summary>

can_reach_server | ok
-- | --

</details>

**Comment by PiterPiotr** [comment]
My configuration:
## System Health

version | core-2022.3.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.92-v8
arch | aarch64
timezone | Europe/Warsaw

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4932
Installed Version | 1.23.0
Stage | running
Available Repositories | 1007
Downloaded Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.5
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.4
docker_version | 20.10.9
disk_total | 58.0 GB
disk_used | 5.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.105.2), Samba share (9.5.1), File editor (5.3.3), InfluxDB (4.3.0), Grafana (7.5.0), Terminal & SSH (9.3.0), Mosquitto broker (6.0.1), Node-RED (11.1.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 7
views | 5
mode | storage

</details>

**Comment by cichytom** [comment]
My configuration:

## System Health

version | core-2022.2.9b0
-- | --
installation_type | AIS HA
dev | false
hassio | false
docker | false
user | u0_a62
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 3.14.29
arch | armv8l
timezone | Europe/Warsaw

<details><summary>Airly</summary>

can_reach_server | ok
-- | --
requests_remaining | 63
requests_per_day | 100

</details>

<details><summary>GIOŚ</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 0
views | 23
mode | storage

</details>

**Comment by PiotrMachowski** [comment]
Fixed in `v2.0.0`
