### ISSUE TITLE
Brak atrybutu "distance" w sensorach burzowych

### ISSUE THREAD

**Issue by rafkan20** [PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net#23]
W poprzednich wersjach w atrybutach sensorów burzowych był dostępny parametr "distance".
Jest możliwość dodania tego atrybutu?
Pozdrawiam.

**Comment by PiotrMachowski** [comment]
Atrybut cały czas jest dostępny, ale tylko jak sensor wykryje burzę (czyli tak samo, jak do tej pory)
