### ISSUE TITLE
Zniknaly wszystkie encjo po update do v2.00

### ISSUE THREAD

**Issue by mskiba03** [PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net#25]
Witam, po aktualizacji do wersji v2.0 zniknely encje, dostalem komunikat ze w pliku configuration.yaml nie wspiera juz wpisów binary_sensor. Usunalem to z konfiguracji, blad znikna. Ale encji nadal nie ma. Gdzie teraz wpisac klucz api i gdzie sa wogole ustawienia?

**Comment by PiotrMachowski** [comment]
W release notkach była informacja, że trzeba usunąć z yamla i dodać integrację z listy integracji

[![Open your Home Assistant instance and start setting up a new integration.](https://my.home-assistant.io/badges/config_flow_start.svg)](https://my.home-assistant.io/redirect/config_flow_start/?domain=burze_dzis_net)
