### ISSUE TITLE
The burze_dzis_net platform for the binary_sensor integration does not support platform setup.

### ISSUE THREAD

**Issue by JacekJI** [PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net#29]
Hi,

After last update integration i lost my sensors.

Information from logs:

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:211
Integration: Sensor binarny (documentation, issues)
First occurred: 12:21:27 (1 occurrences)
Last logged: 12:21:27

The burze_dzis_net platform for the binary_sensor integration does not support platform setup. Please remove it from your config.

**Comment by PiotrMachowski** [comment]
Everything is written in release notes
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net/releases/tag/v2.0.0

**Comment by JacekJI** [comment]
clear
