### ISSUE TITLE
it's not an issue, it's a little bit request. :0) 

### ISSUE THREAD

**Issue by caiosweet** [PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net#3]
Hello.
Is it possible to add the coordinates (long, lat) of the lightning closest to home, to the attributes of the nearby storm sensor?
Thanks

**Comment by PiotrMachowski** [comment]
Hi, unfortunately API doesn't provide this information, so I can't do anything about it :(

**Comment by caiosweet** [comment]
Oh, don't worry it was one more thing. Thank you very much. :0)
