### ISSUE TITLE
Impossible to install or update component using HACS

### ISSUE THREAD

**Issue by nepozs** [PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net#30]
Affected versions [v2.0.0](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net/releases/tag/v2.0.0) and 
v1.0.4 

possible reason  bad `hacs.json`

**Comment by nepozs** [comment]
Still impossible, so change in `hacs.json` isn't enough…

**Comment by PiotrMachowski** [comment]
Do you have anything in logs?

**Comment by PiotrMachowski** [comment]
I have just installed without any issues using HACS 1.33.0

**Comment by nepozs** [comment]
Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:986
Integration: HACS (documentation, issues)
First occurred: 22:44:30 (1 occurrences)
Last logged: 22:44:30

<Integration PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net> Failed to download https://github.com/PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net/releases/download/tags/v2.0.0/antistorm.zip

I will try to reboot HAOS.
Now v1.03 is installed and update fails. HA restarts have not helped.

## System Information

version | core-2024.2.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4982
Installed Version | 1.34.0
Stage | running
Available Repositories | 1387
Downloaded Repositories | 21

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 57.8 GB
disk_used | 11.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Samba share (12.3.0), Advanced SSH & Web Terminal (17.1.0), AirCast (4.2.0), Glances (0.21.0), FTP (5.0.1), Spotify Connect (0.13.0), Tailscale (0.15.0), ZeroTier One (0.18.0), AIS Cloudflared (0.1.13), go2rtc (1.8.5), Home Assistant Google Drive Backup (0.112.1), A better presence (1.2.0), Mosquitto broker (6.4.0), chrony (3.0.1), rtl_433 (0.4.0), rtl_433 MQTT Auto Discovery (0.6.0), MQTT Explorer (browser-1.0.1), Samba NAS (12.2.0-nas1), Music Assistant BETA (2.0.0b92), ESPHome (2023.12.9)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 8
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 31 stycznia 2024 21:42
-- | --
current_recorder_run | 10 lutego 2024 21:35
estimated_db_size | 480.56 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

**Comment by nepozs** [comment]
Last try
```
Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:986
Integration: HACS (documentation, issues)
First occurred: 10 lutego 2024 23:19:03 (3 occurrences)
Last logged: 00:16:44

<Integration PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net> Failed to download 

https://github.com/PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net/releases/download/tags/v2.0.0/antistorm.zip
<Integration PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net> Failed to download https://github.com/PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net/releases/download/master/burze_dzis_net.zip
```

**Comment by PiotrMachowski** [comment]
I think I'll create a new release to fix it...

**Comment by PiotrMachowski** [comment]
I have created a new release, can you check if it helped?
