### ISSUE TITLE
Provide entities aggregating all alerts and all active alerts 

### ISSUE THREAD

**Issue by pskowronek** [PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net#33]
Provide entities aggregating all alerts and all active alerts - now when I wanted to conditionally display a card or ticker when there's alert, I need to create conditions for every binary sensor like wiatr, upal, trąba etc. 

If there were 2 binary sensors like `binary_sensor.burze_dzis_net_ostrzezenia` and `binary_sensor.burze_dzis_net_ostrzezenia_aktywne` aggregating all sensor, then it would be easier. Open question is how to aggregate them - attributes listing all of them when active, or concatenated?

I would be nice to be able to configure what types of alerts it should aggregate.

BTW, great job - nice integration!

**Comment by PiotrMachowski** [comment]
It is not recommended to create such aggregation entities by the integration. Additionally it is quite easy to create it as a template entity
