### ISSUE TITLE
Raspberry Pi4 support

### ISSUE THREAD

**Issue by gridi88** [PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net#4]
hello, can you add Raspberry Pi 4 support?  What I understood lacked libraries. Does not work. Thank you.

**Comment by PiotrMachowski** [comment]
Could you provide more information about your issue? Does anything appear in logs? What platform do you use?

**Comment by gridi88** [comment]
Thank you for the support. 
Latest Image HassOS on Raspberry Pi4 4GB. Log https://pastebin.com/87jnYKqc
Natural Events Package on [HassioHelp](https://hassiohelp.eu/2019/10/06/package-eventi-naturali/)
![HassioHelp_eu](https://user-images.githubusercontent.com/38946221/67568796-78930200-f72d-11e9-840f-c20fd899efea.png)

**Comment by gridi88** [comment]
I forgot to add that on the Raspberry 3b everything runs smoothly.

**Comment by PiotrMachowski** [comment]
Do they have the same configuration? Could you share them? There seems to be an issue with coordinates.
If you don't want to share config publicly you can send it via email.

**Comment by gridi88** [comment]
In fact, now i tried to declare the coordinates on configuration.yaml and it started working.  
For whom do the coordinates state them on Settings/General how should it do?

**Comment by PiotrMachowski** [comment]
By default coordinates are taken from home location. You can override these values by defining `longitude` and `latitude` in sensors settings
