### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by mgiako** [PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net#6]
In HomeAssistant 0.109.0b0 I have the folowing warning:

Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 1:09:34 PM (539 occurrences)
Last logged: 5:13:47 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for burze_dzis_net doing I/O at custom_components/burze_dzis_net/binary_sensor.py, line 203: service = Client('https://burze.dzis.net/soap.php?WSDL').service

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for burze_dzis_net doing I/O at custom_components/burze_dzis_net/binary_sensor.py, line 205: self.ostrzezenia_pogodowe_output = service.ostrzezenia_pogodowe(self._y, self._x, self._api_key)

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for burze_dzis_net doing I/O at custom_components/burze_dzis_net/binary_sensor.py, line 206: self.szukaj_burzy_output = service.szukaj_burzy(self._y, self._x, self._radius, self._api_key)

**Comment by jokerigno** [comment]
Same issue in 0.109

**Comment by alesoft73** [comment]
I too!

**Comment by fabioxp7980** [comment]
same issue, don't know how to fix, only read about async but nothing else

**Comment by riddik14** [comment]
same issue...?

WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for burze_dzis_net doing I/O at custom_components/burze_dzis_net/binary_sensor.py, line 206: self.szukaj_burzy_output = service.szukaj_burzy(self._y, self._x, self._radius, self._api_key)

**Comment by PiotrMachowski** [comment]
The same issue. It will be present for everyone using version 0.109. I am working on the fix.

**Comment by PiotrMachowski** [comment]
Fixed in release v1.0.1
