### ISSUE TITLE
Add sensor entities

### ISSUE THREAD

**Issue by Dawider10** [PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net#8]
I think having weather warnings as sensors with warning level as state would be better.
Instead of just 'on/off' we would have information about warning level available immediately in the UI and in history.
Right now we have to create template sensors to make warning level visible.

**Comment by PiotrMachowski** [comment]
I think I can easily add it as an additional sensor, I will do it in a free time

**Comment by murcin** [comment]
I`ve try to integrate to HomeAssistant and I do it like in instruction - install in HACS copy API bu still is not avaiable in Entieties.... 
any sugestion ?

`binary_sensor:
  - platform: burze_dzis_net
    api_key: c1171....................................2a31
    warnings:
      - frost_warning
      - heat_warning
      - wind_warning
      - precipitation_warning
      - storm_warning
      - tornado_warning
    storms_nearby:
      radius: 30`

![image](https://user-images.githubusercontent.com/66697668/88848528-e0a8d400-d1e8-11ea-81e7-7547e35656c7.png)

**Comment by MSzczesiak-SH** [comment]
@PiotrMachowski Did you have some spare time to make this happen ? I have added this integration with HACKS and i can only see binary sensors with on/off state

**Comment by PiotrMachowski** [comment]
@MSzczesiak-SH not really, other integrations got higher priority

**Comment by MSzczesiak-SH** [comment]
> @MSzczesiak-SH not really, other integrations got higher priority

Any chances on this one to be done ? Or at least ETA ? No rushing, just asking.

**Comment by PiotrMachowski** [comment]
@MSzczesiak-SH I plan to do it, but I have a loooooooooot of work with other HA stuff (mostly related to Xiaomi Vacuums), so unfortunately I can't provide any ETA

**Comment by MSzczesiak-SH** [comment]
> @MSzczesiak-SH I plan to do it, but I have a loooooooooot of work with other HA stuff (mostly related to Xiaomi vacuums), so unfortunately I can't provide any ETA

Fair enough. Thnx for the answer.

**Comment by fcqpl** [comment]
Hi @PiotrMachowski , any update? :)

**Comment by PiotrMachowski** [comment]
Hi @fcqpl 

I have pulled an all-nighter, buuuut I have rewritten the integration from the scratch. `v2.0.0` coming soon

**Comment by PiotrMachowski** [comment]
Added in `v2.0.0`

**Comment by fcqpl** [comment]
Hi @PiotrMachowski, thanks for update!
Could you also add:
- lightning counter
- distance to lightning and it's direction?

Like on website:
```
Zarejestrowano w ciągu 10 minut, 2 wyładowania atmosferyczne w wybranym promieniu. Najbliższe wyładowanie atmosferyczne 28,53 km na północny zachód od wskazanej lokalizacji.
```

**Comment by PiotrMachowski** [comment]
Lightning counter has also been added in v2.0.0, distance, period and direction are currently available in attributes of lightning-related entities

**Comment by fcqpl** [comment]
Oh, I found it. Thanks!
